import manifest from './asset-manifest.json'

const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? ''
const versions: Record<string, string> = manifest

/**
 * Adds the content version of an asset, so a replaced photo gets a URL no
 * browser has cached. Generated by scripts/generate-asset-manifest.mjs.
 */
export function versioned(path: string): string {
  const version = versions[path]
  return version ? `${path}?v=${version}` : path
}

export function asset(path: string): string {
  return `${BASE}${versioned(path)}`
}

/** Versioned absolute URL, for OG tags and share links. */
export function absoluteAsset(origin: string, path: string): string {
  return `${origin.replace(/\/$/, '')}${versioned(path)}`
}
