import { asset } from './assetPath'
import blurManifest from './photo-blur.json'

const blurs: Record<string, string> = blurManifest

/**
 * The inlined 16px preview of a photo, which next/image paints behind the real
 * file while it downloads. Generated by scripts/optimize-photos.mjs.
 */
export function blurDataURL(path: string): string | undefined {
  return blurs[path]
}

export interface GalleryPhoto {
  /** Small crop for the 2-column grid. */
  thumb: string
  thumbBlur?: string
  /** Bigger version, only loaded once a photo is opened in the lightbox. */
  full: string
  fullBlur?: string
}

const ORDER = ['photo-01', 'photo-02', 'photo-05', 'photo-06', 'photo-03', 'photo-04']

export const galleryPhotos: GalleryPhoto[] = ORDER.map(name => ({
  thumb: asset(`/photos/${name}-thumb.webp`),
  thumbBlur: blurDataURL(`/photos/${name}-thumb.webp`),
  full: asset(`/photos/${name}.webp`),
  fullBlur: blurDataURL(`/photos/${name}.webp`),
}))

export const mainPhoto = {
  src: asset('/photos/main.webp'),
  blur: blurDataURL('/photos/main.webp'),
}
